In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

In [2]:
data =load_digits()

In [3]:
dir(data)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(data.data,data.target)

In [85]:
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression


In [22]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [28]:
from sklearn.model_selection import StratifiedKFold

In [106]:
f = StratifiedKFold(n_splits=3)

In [81]:
def get_scores(model,X_train,X_test,Y_train,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)

In [92]:
get_scores( RandomForestClassifier(),X_train,X_test,Y_train,Y_test)
s = []
lr = []

In [112]:
for train_index,test_index in f.split(data.data,data.target):
    X_train,X_test,Y_train,Y_test = data.data[train_index],data.data[test_index],data.target[train_index],data.target[test_index]
    s.append(get_scores(RandomForestClassifier(), X_train,X_test,Y_train,Y_test))
    lr.append(get_scores(LogisticRegression(max_iter=10000), X_train,X_test,Y_train,Y_test))

In [113]:

print(lr)

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498, 0.9248747913188647, 0.9382303839732888, 0.9232053422370617, 0.9248747913188647, 0.9382303839732888, 0.9232053422370617, 0.9215358931552587, 0.9415692821368948, 0.9165275459098498, 0.9248747913188647, 0.9382303839732888, 0.9232053422370617, 0.9248747913188647, 0.9382303839732888, 0.9232053422370617]


In [117]:
from sklearn.model_selection import cross_val_score

In [119]:
cross_val_score(LogisticRegression(max_iter=100000),data.data,data.target)

array([0.925     , 0.875     , 0.93871866, 0.93593315, 0.89693593])

In [121]:

from sklearn.svm import SVC


array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [122]:
cross_val_score(RandomForestClassifier(),data.data,data.target)

array([0.925     , 0.925     , 0.95543175, 0.96935933, 0.93036212])