In [19]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline
from word2number import w2n

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv")

In [3]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
da = data["test_score(out of 10)"].median()
da

8.0

In [5]:
data['test_score(out of 10)'] = data['test_score(out of 10)'].fillna(da)

In [21]:

zero = "zero"
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [22]:
data.experience = data.experience.fillna(zero) 


In [23]:
data


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [26]:
data.experience = data.experience.apply(w2n.word_to_num)

In [27]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [28]:
reg = linear_model.LinearRegression()

In [29]:
reg

LinearRegression()

In [31]:
reg.fit(data[['experience','test_score(out of 10)','interview_score(out of 10)']],data['salary($)'])

LinearRegression()

In [33]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [34]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [35]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [39]:
reg.intercept_

17737.26346433771

In [ ]:
y = m1*x + m2*x + m3*x + c 


In [40]:
2812.95487627*2 + 1845.70596798*9 + 2205.24017467*6 + 17737.26346433771

53205.967976717715