In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline

In [4]:
data = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv")

In [6]:
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
m = data['bedrooms'].median()

In [8]:
data


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
data.bedrooms = data.bedrooms.fillna(m)

In [11]:
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [12]:
reg = linear_model.LinearRegression()

In [13]:
reg

LinearRegression()

In [14]:
reg.fit(data[["area","bedrooms","age"]],data.price)

LinearRegression()

In [15]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
reg.intercept_

221323.00186540408

In [17]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [18]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In [ ]:
y=m1*x+m2*x+m3*x +c 
